### PR TITLE
harmonize actors, apps

### PR DESCRIPTION
**Pull request by psadil**

### CODE REVIEW

**Comment by psadil** [comment]
need to test
- [x] qsiprep_app /corral-secure/projects/A2CPS/shared/psadil/jobs/fea9afa6-3189-4ef2-80b4-82e5c2c73d37-007
- [ ] qsiprep_actor
- [x] gift_app: /corral-secure/projects/A2CPS/shared/psadil/jobs/0dd4b796-887e-4d2c-a8f4-2c3fd01ac848-007
- [x] gift_actor: /corral-secure/projects/A2CPS/shared/psadil/jobs/46ae8378-2a7b-4570-9d11-2c07bdc74727-007
- [x] mriqc_actor: /corral-secure/projects/A2CPS/shared/psadil/jobs/1e61791d-7217-4055-9135-4409eff70534-007
- [ ] brainager_actor
- [x] fslanat_actor: /corral-secure/projects/A2CPS/shared/psadil/jobs/becaad35-b9c4-4c86-9046-908b629f50d1-007
- [x] aggregator_actor: /corral-secure/projects/A2CPS/shared/psadil/jobs/ecfd0e66-7fdf-4a4c-acaa-9845e9d1e28e-007
- [x] aggregator_qc_actor: /corral-secure/projects/A2CPS/shared/psadil/jobs/2da96a5d-0f44-4081-b2dd-1cc602e47e57-007

**Comment by JoshuaUrrutia** [comment]
gift app/actor deployed
aggregator app/actor deployed
mriutils hash updated

**Comment by JoshuaUrrutia** [comment]
updated gift app deployed

**Comment by JoshuaUrrutia** [comment]
updated gift and qsiprep actors deployed

**Pull request merged**
