### PR TITLE
handle a few known cases of atypical names from one UM scanner

### LINKED ISSUE #37: some UM scans have atypical PatientName tags
For background, see slack threads https://a2cps-pain.slack.com/archives/C02JP3G763X/p1635429486032800 and https://a2cps-pain.slack.com/archives/C02JP3G763X/p1635438080037500 .

### PR DESCRIPTION
**Pull request by psadil**
Close #37 

See slack threads in associated issue and Confluence page (https://confluence.a2cps.org/display/DOC/Imaging+Log+-+Problem+Cases) for background. This pull request adds additional logic to standardize the names of participants 

UM20020V1 -> cmb21a2c20020
UM20021V1 -> cmb21a2c20021
UM20022V1 -> cmb21a2c20022
UM20023V1 -> cmb21a2c20023
UM20024V1 -> cmb21a2c20024
UM20025V1 -> cmb21a2c20025

There is no need to incorporate these changes immediately, since they have been manually forced through the pipeline. But the changes should be merged at any subsequent re-run of the dicom_reader_app

### CODE REVIEW

**Comment by JoshuaUrrutia** [comment]
Do we know the `cmb21a2c` portion means V1?

This could attempt an overwrite for example if `UM20020V3` were also submitted with:
`cmb21a2c20020`

**Comment by psadil** [comment]
I see your point. I was thinking that we can expect typical names moving forward, and so that by the time V3 happens we'll be getting dicoms with more standard PatientName tags (e.g., no more cases with `cmb21ac` in the tag). If we did start getting standard names, how would you feel about the hard assumption this commit makes about V1?

(I guess that's another good reason to not merge this immediately, so that we can confirm it'll be possible to receive correctly named participants from this scanner)

**Comment by JoshuaUrrutia** [comment]
If we don't have complete  information (site, subject, visit) included in the patientID, I don't think we should write code that manufactures that information. 

We can just use the existing mechanism of defining the subject_id in the job.json. 

In the cases where we're missing information, we *want* manual/human review. 
Otherwise, these cases could go unnoticed and our V1 assumption could be incorrect.

**Comment by psadil** [comment]
Do you mean having separate job.json files that need to get run manually anytime these six participants are run through the dicom app? I guess I'm thinking that might be a lot to keep track of and easy to miss -- both for us and anyone that receives these data down the line. I was hoping these edits would make it so that we don't need manual solutions next time around.

If there is a concern about `cmb21a2c` matching participants down the line, we could also remove the regex match and instead use a more verbose `if else` clause, e.g.,

```
if std_name == "cmb21a2c20020":
  subject_id = 20020
  session_id = "V1"
  site_id = "UM"
  # <if desired, also print to log / send slack notification >
elif std_name == "cmb21a2c20021":
  subject_id = 20021
  session_id = "V1"
  site_id = "UM"
  # <if desired, also print to log / send slack notification >
[...]
```
Or, are you thinking it's likely that we're going to receive another dicom with the PatientName tag set to `cmb21a2c20020`?

edit: The thinking being that this is the same logic that would be use to create a job.json, so we might as well put it in the code base. If we wanted to be extra cautious, we could also add a check for when the zip file was created, to avoid the case of `cmb21a2c20020` being reused.

**Pull request closed without merging**
